test9 (1)/test9/test9/test9/test9/Controllers/AssignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using test9.Models;

namespace test9.Controllers
{
    public class AssignsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Assigns
        public ActionResult Index()
        {
            var assigns = db.Assigns.Include(a => a.Course).Include(a => a.Trainee);
            return View(assigns.ToList());
        }

        // GET: Assigns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assign assign = db.Assigns.Find(id);
            if (assign == null)
            {
                return HttpNotFound();
            }
            return View(assign);
        }




        public ActionResult GetCourse(string id)
        {
            var course = db.Assigns.Where(t => t.Id == id).ToList();
            return View(course);

        }
        // GET: Assigns/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName");
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "Email");
            return View();
        }

        // POST: Assigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssignID,CourseID,Id")] Assign assign)
        {
            if (ModelState.IsValid)
            {
                db.Assigns.Add(assign);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", assign.CourseID);
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "Email", assign.Id);
            return View(assign);
        }

        // GET: Assigns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assign assign = db.Assigns.Find(id);
            if (assign == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", assign.CourseID);
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "Email", assign.Id);
            return View(assign);
        }

        // POST: Assigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AssignID,CourseID,Id")] Assign assign)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assign).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", assign.CourseID);
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "Email", assign.Id);
            return View(assign);
        }

        // GET: Assigns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assign assign = db.Assigns.Find(id);
            if (assign == null)
            {
                return HttpNotFound();
            }
            return View(assign);
        }

        // POST: Assigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Assign assign = db.Assigns.Find(id);
            db.Assigns.Remove(assign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

test9 (1)/test9/test9/test9/test9/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("FPT Internal Training System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @if (User.IsInRole("Trainee"))
                {
                @Html.ActionLink("View my course",  "GetCourse", "Assigns", new { id = User.Identity.GetUserId() }, new { @class = "navbar-brand" })
                }
                            </div>
            <div class="navbar-collapse collapse">
                <!--<ul class="nav navbar-nav">
         <li>@Html.ActionLink("Home", "Index", "Home")</li>

     </ul>-->
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center"> &Eta;&Epsilon;&Gamma;&Gamma;&Ouml;   &Kappa;&Icirc;&Tau;&tau;&upsih;  </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<link href=".\CSS\style.css" rel="stylesheet">